spring:
  application:
    name: moon_spring
  #mysql连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moondb
    username: moon
    password: dcncloud
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    开起了驼峰命名
    map-underscore-to-camel-case: true

server:
  port: 9876